[gcp_service_account]
type = "service_account"
project_id = "workout-tracker-461712"
private_key_id = "f22f262e6addb9b5e3fb27993f8d1189953fe065"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmXNIqdsSUNXkm
av5mRhoE5YF/3/YSw0XpBDIouTC6QxX/YNc/ww0qPahXZSEHeK4ZY0zDV6hU42++
kIsvAC9RTcpLG+ij5mM/Thv6u+kd9IHE4VComWRL9mkuiP5NyFsRb4sck79Z6wJi
rLlNHioi8kdqd54O8h09ExrwnmqLQTWTufhzXrk3OTP5adc3Xmbs3ymWWUOgD9P4
7XEikjKq6CInMKNLEXHVmNdyoqSSa2/3YLnmdu4izYFdNkNclk6lTR083TRuSYPB
KEX+yKrNoOoT99vbaCJrRbLwIG7gLEm4ewYmFeWMd1udid5A9M5aXxijMRxGTyuB
SVSFIyiVAgMBAAECggEAN+U8+eaAwvk6dNWDF1LbYCTKf2/8yi4Q+asevT8Hp7Vt
mSns+G/tJvGjc4W3dL6v5DjQbFux45+tBl6jXQ3XWB5mZxj/772zP+xbC0ICn71s
sn0vsA4lvD4U9f0yUGkObAvJtjbQFoKXARdehRIq/yXfJ9773LKtbz1RkmHvk0yw
7iRXs1ZFGO5zk2ppRilU03gsSHKE5KtCFDXADq8X5b0FpkIGd6MD+5EqB9f1Htri
4pnYgNMD/eX7wnfil1QfDgG3TQkoxyyuMowptxXG77cWQ+JrHWg7Nxuidc7vN/0W
Ox7Trkzn1UWrvGXfT/1JnP9yvnsYUDQ0scVQeo8EqwKBgQDgU+5WZE+B2EbZDqes
w6jdh2DCR5DfFuOFl/s0SNB90FK/4Yag5GcOEtvdzR7unetahmg4Qa+Y05v4jTIw
s4PbKS25HAqc/qCV/48TOrYAHx+DlSAmKFTvLaKLeqsHwGR3oH3574h9kkca7Qzf
fsgmn59mfFS+AevKr1E/hwiLAwKBgQC92c17wTM3luWDmp1HqtynGPiXKj6P1D8g
OT7H0s7vm6uIZv/yU30U4H5NxEzpaIu2fFCo6KDLhK9uYZt78wja66AANf/81zC+
73n6skSH2CHeiO0UFnNVqV26dBx4DvLCTBt/qIt8fscfvAsWHeocvJRGjDIGjoKJ
h3Oli/KehwKBgQCBQLrl+jw5Y2VG8YO5Lq9gnP0qU9PsRqLnua8a7A19QIg9WPOa
Rp/+Yu1eOi7lbAZMjX8FUwubMen/Z1OQ7g4+O9bFfpu645ehdbN5b+2n2kbtKQJy
GfD+MrwiQ5bCC5+XsdiEJvjs6Vig8g7lw4YNgxF0GpU1OaQjj6pvwR0yAwKBgFy3
b7jOg7rUQMZizgjgEt6wPUdl5CPN3f5YtqZT96fg+Iam9rxbtaxqboSAJ6ed3Q2D
7Mhww4ZhCGP52ztPV7XCeONhe+D5Ht9AiOu7/+fvz6qkaFP1GuJs0k9qwTSI6Fmn
XY6cu3JTX9/JsAhfF6RtHGTPtuao1mtf8USZ8iUlAoGAfATj2/peZUgdfinw5zoP
JmEtkjBQ8mXg1YV0h2RnCyYbwj06nFg5MZS2eu05tow44GhbI81fW6u6zIMgccbG
YzYU6RXyvbYx3cubzmsgFQJlSojpxWmuYUkY3sA0/bkjUD6B3qOKPjKOrOXk07AW
E19hMku9HuBJ2WLGiKqHze8=
-----END PRIVATE KEY-----"""

client_email = "streamlit-sheets-access@workout-tracker-461712.iam.gserviceaccount.com"
client_id = "115991757052400861345"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets-access%40workout-tracker-461712.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[general]
gsheet_id = "1MS0TYrMP_7rrsf9Trv50sqxJnk_837rLebtKXbpHKxA"